### ISSUE TITLE
1.1.1 for 1.12.2 Server Crash looking for GUI

### ISSUE THREAD

**Issue by kreezxil** [shock-metal/shock-metal#10]
**Describe the bug**

https://pastebin.com/RP6tDnqK

**To Reproduce**
1. install 1.12.2 forge using build 2860
2. install 1.1.1 for 1.12.2 shock metal
3. create a server pack of it
4. run it
5. enjoy error
 
**Expected behavior**
not crash the server

**Minecraft (please complete the following information):**
- Minecraft Version: 1.12.2
- Forge Version: 14.23.5.2860
- Mod Version: 1.1.1 for 1.12.2

**Additional context**
sever crash report: https://pastebin.com/RP6tDnqK

**Comment by vNemesis** [comment]
Unable to get a fix for this as the version is too old unfortunately
