### ISSUE TITLE
Sudden crash for the 1.16.4-1.0.2 file on 1.16.3 version

### ISSUE THREAD

**Issue by YT-Brawlertomi** [shock-metal/shock-metal#5]
I was excited to play on my minecraft world with this new mod, because i think its original and has a big potential, however, when i was starting the game on my launcher, the game opened for a few moments and then it crashes, i checked on the developer console from my launcher and it said this:

[main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/]: Missing language javafml version [35,) wanted by shockmetal-1.16.4-1.0.2.jar, found 34.1

as my 3 braincells can read it says some kind of missing language and well, i dont know what to do, i really want to play with this mod and also add it to my server, but if i install old versions of this mod i dont know if im going to be able to wear the full setof the armor because as i saw, on the 1.0.2 version of the mod the bug of the sudden crash of the server after wear the full set of the armor was fixed, so if i install another version the server may crash, and i need this mod for 1.16.3 but if the game wont even load because of this error i dont know what im going to do, please help i really enjoy the content and how this mod looks like  :(

**Comment by YT-Brawlertomi** [comment]
i accidentally closed the issue lmao sorry

**Comment by vNemesis** [comment]
Hey,

The mod required Forge version 35 for MC 1.16.4 as minimum and it seems you are using version 34.1 for MC 1.16.3

I may have accidentally added the 1.16.3 tag for the previous builds, if so ill correct it but yeah the mod was updated to the 1.16.4 forge version.

I can take a look at making a 1.16.3 version but I would say it's probably better to upgrade to 1.16.4 or 1.16.5 :)

I'll update here on progress

**Comment by vNemesis** [comment]
Also the armour bug should only be in version 1.0.0 & 1.0.1, any version other than those two should be fine for server use

**Comment by vNemesis** [comment]
What forge version is your server using?

**Comment by vNemesis** [comment]
just uploaded a new version, it says 1.16.5-1.1.1 but should work for 1.16.3 as well. you need to ensure you have forge 34.1.40 or higher. most of the mods i tested it with used that version.
